//! `pipeline_env` handler · environment scaffolding · deps · secrets.
//!
//! Day-6 wires: create, deps_install, deps_audit, secrets_setup.
//! Other 6 actions return not_implemented (MVP).

#![allow(clippy::doc_markdown)]

use crate::server::ServerState;
use crate::tools::{ToolName, ToolRequest, ToolResponse};
use serde_json::{Value, json};
use std::fmt::Write as _;
use std::sync::Arc;
use tokio::process::Command;

pub async fn handle(req: ToolRequest, _state: Arc<ServerState>) -> ToolResponse {
    match req.action.as_str() {
        "create" => create(&req.args).await,
        "deps_install" => deps_install(&req.args).await,
        "deps_audit" => deps_audit().await,
        "secrets_setup" => secrets_setup(&req.args).await,
        "deps_update" | "deps_lock" | "runtime_provision" | "tooling_install"
        | "secrets_inject" | "devcontainer_open" => {
            ToolResponse::not_implemented(ToolName::Env, &req.action)
        }
        other => err(format!("unknown action 'pipeline_env.{other}'")),
    }
}

async fn create(args: &Value) -> ToolResponse {
    let cwd = match std::env::current_dir() {
        Ok(p) => p,
        Err(e) => return err(format!("cwd: {e}")),
    };
    let profile = args
        .get("profile")
        .and_then(Value::as_str)
        .unwrap_or("default");
    let mut written: Vec<String> = Vec::new();

    let env_path = cwd.join(".env.example");
    if !env_path.exists() {
        if let Err(e) = tokio::fs::write(&env_path, ENV_EXAMPLE).await {
            return err(format!("write .env.example: {e}"));
        }
        written.push(env_path.display().to_string());
    }

    let dc_dir = cwd.join(".devcontainer");
    if let Err(e) = tokio::fs::create_dir_all(&dc_dir).await {
        return err(format!("mkdir .devcontainer: {e}"));
    }
    let dc_path = dc_dir.join("devcontainer.json");
    if !dc_path.exists() {
        if let Err(e) = tokio::fs::write(&dc_path, DEVCONTAINER_JSON).await {
            return err(format!("write devcontainer.json: {e}"));
        }
        written.push(dc_path.display().to_string());
    }

    ToolResponse {
        ok: true,
        data: json!({"profile": profile, "files_written": written}),
        next_suggested: vec![
            "pipeline_env.deps_install".into(),
            "pipeline_env.secrets_setup".into(),
        ],
        memory_refs: vec![],
        error: None,
    }
}

async fn deps_install(args: &Value) -> ToolResponse {
    let stack = args.get("stack").and_then(Value::as_str).unwrap_or("rust");
    let cwd = match std::env::current_dir() {
        Ok(p) => p,
        Err(e) => return err(format!("cwd: {e}")),
    };
    let (program, cmd_args): (&str, Vec<&str>) = match stack {
        "rust" => ("cargo", vec!["fetch"]),
        "node" | "ts" | "typescript" => ("npm", vec!["install"]),
        "bun" => ("bun", vec!["install"]),
        "python" | "python-uv" | "uv" => ("uv", vec!["sync"]),
        "go" | "golang" => ("go", vec!["mod", "download"]),
        other => return err(format!("unsupported stack '{other}'")),
    };
    run_capture(program, &cmd_args, &cwd, &format!("deps_install({stack})")).await
}

async fn deps_audit() -> ToolResponse {
    let cwd = match std::env::current_dir() {
        Ok(p) => p,
        Err(e) => return err(format!("cwd: {e}")),
    };
    // Try cargo audit first · falls back with helpful error if not installed.
    run_capture("cargo", &["audit"], &cwd, "deps_audit").await
}

async fn secrets_setup(args: &Value) -> ToolResponse {
    let cwd = match std::env::current_dir() {
        Ok(p) => p,
        Err(e) => return err(format!("cwd: {e}")),
    };
    let names: Vec<String> = match args.get("keys").and_then(Value::as_array) {
        Some(a) => a
            .iter()
            .filter_map(|v| v.as_str().map(str::to_owned))
            .collect(),
        None => vec!["DATABASE_URL".into(), "API_KEY".into()],
    };

    let mut body = String::from("# Generated by pipeline_env.secrets_setup · placeholders only\n");
    for k in &names {
        writeln!(body, "{k}=__SET_ME__").ok();
    }
    let path = cwd.join(".env.example");
    if let Err(e) = tokio::fs::write(&path, body).await {
        return err(format!("write .env.example: {e}"));
    }
    ToolResponse::ok(json!({
        "path": path.display().to_string(),
        "keys": names,
    }))
}

async fn run_capture(
    program: &str,
    args: &[&str],
    cwd: &std::path::Path,
    label: &str,
) -> ToolResponse {
    let output = match Command::new(program)
        .args(args)
        .current_dir(cwd)
        .output()
        .await
    {
        Ok(o) => o,
        Err(e) => return err(format!("{program} spawn: {e} · is it installed?")),
    };
    let ok = output.status.success();
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    ToolResponse {
        ok,
        data: json!({
            "command": label,
            "exit_code": output.status.code().unwrap_or(-1),
            "stdout": truncate(&stdout, 8_000),
            "stderr": truncate(&stderr, 8_000),
        }),
        next_suggested: vec![],
        memory_refs: vec![],
        error: if ok {
            None
        } else {
            Some(format!(
                "{label} exit {}",
                output.status.code().unwrap_or(-1)
            ))
        },
    }
}

const ENV_EXAMPLE: &str = "# Copy to .env and fill in real values · NEVER commit .env.\nDATABASE_URL=postgres://user:pass@localhost:5432/db\nAPI_KEY=__SET_ME__\nLOG_LEVEL=info\n";

const DEVCONTAINER_JSON: &str = "{\n  \"name\": \"pipeline-dev\",\n  \"image\": \"mcr.microsoft.com/devcontainers/base:bookworm\",\n  \"features\": {\n    \"ghcr.io/devcontainers/features/rust:1\": {},\n    \"ghcr.io/devcontainers/features/docker-in-docker:2\": {}\n  },\n  \"postCreateCommand\": \"cargo --version && docker --version\"\n}\n";

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_owned()
    } else {
        let mut t = s[..max].to_owned();
        write!(t, "\n... [truncated · {} more bytes]", s.len() - max).ok();
        t
    }
}

fn err(msg: String) -> ToolResponse {
    ToolResponse {
        ok: false,
        data: json!({}),
        next_suggested: vec![],
        memory_refs: vec![],
        error: Some(msg),
    }
}

#[cfg(test)]
mod tests {
    use super::truncate;
    #[test]
    fn truncate_keeps_short_strings() {
        assert_eq!(truncate("hi", 100), "hi");
    }
    #[test]
    fn truncate_marks_long_strings() {
        let out = truncate(&"x".repeat(50), 10);
        assert!(out.starts_with("xxxxxxxxxx"));
        assert!(out.contains("truncated"));
    }
}
